//go:build cgo

package fix

import (
	"context"
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/steveyegge/beads/internal/configfile"
	"github.com/steveyegge/beads/internal/storage/dolt"
	"github.com/steveyegge/beads/internal/storage/doltutil"
	"github.com/steveyegge/beads/internal/testutil"
	"github.com/steveyegge/beads/internal/types"
)

// fixTestServerPort returns the Dolt server port for fix tests.
// Uses DoltContainerPortInt so the port is only non-zero when TestMain
// actually started a container, ignoring any external BEADS_DOLT_PORT.
func fixTestServerPort() int {
	return testutil.DoltContainerPortInt()
}

// requireFixDoltContainer enforces the Dolt test container precondition for
// the DB-backed fix tests. Locally a missing container skips, so contributors
// without Docker stay green. A CI job that sets BEADS_FIX_REQUIRE_DOLT=1
// (after pulling the Dolt image) turns the missing container into a hard
// failure instead — the guard that keeps this suite from silently going dark
// again (bd-nxt5e: every DB-backed test here skipped for months, locally and
// in CI, with nothing noticing). Once the container IS up, dolt.New failures
// must be t.Fatal, never t.Skip.
func requireFixDoltContainer(t *testing.T) {
	t.Helper()
	if fixTestServerPort() != 0 {
		return
	}
	if os.Getenv("BEADS_FIX_REQUIRE_DOLT") == "1" {
		t.Fatal("Dolt test container unavailable but BEADS_FIX_REQUIRE_DOLT=1; the fix-package DB suite must not silently skip")
	}
	t.Skip("skipping: Dolt test container not available")
}

// newFixTestStore creates a DoltStore for fix package tests with proper
// .beads directory structure so openAnyDB can connect for end-to-end testing.
func newFixTestStore(t *testing.T, dir string, prefix string) *dolt.DoltStore {
	t.Helper()
	ctx := context.Background()

	requireFixDoltContainer(t)
	port := fixTestServerPort()

	// Generate unique database name for test isolation
	h := sha256.Sum256([]byte(t.Name() + fmt.Sprintf("%d", time.Now().UnixNano())))
	dbName := "fixtest_" + hex.EncodeToString(h[:6])

	// Create .beads directory
	beadsDir := filepath.Join(dir, ".beads")
	if err := os.MkdirAll(beadsDir, 0755); err != nil {
		t.Fatalf("Failed to create .beads: %v", err)
	}

	// project_id matched between metadata.json and the database so
	// verifyFixTargetIdentity (mybd-2qegi) doesn't reject these fix calls as
	// unverifiable targets. Mismatch/unverifiable-target cases get their own
	// tests below.
	projectID := configfile.GenerateProjectID()

	// Write metadata.json so openAnyDB can connect to the same database
	cfg := &configfile.Config{
		Database:       "dolt",
		DoltMode:       configfile.DoltModeServer,
		DoltServerHost: "127.0.0.1",
		DoltServerPort: port,
		DoltDatabase:   dbName,
		ProjectID:      projectID,
	}
	if err := cfg.Save(beadsDir); err != nil {
		t.Fatalf("Failed to write metadata.json: %v", err)
	}

	// Create store connected to the same database. CreateIfMissing is
	// required: the per-test database does not exist yet, and dolt.New's
	// create-guard refuses to create it implicitly (bd-nxt5e — its absence
	// made every test using this helper skip).
	dbPath := filepath.Join(beadsDir, "beads.db")
	store, err := dolt.New(ctx, &dolt.Config{
		Path:            dbPath,
		ServerHost:      "127.0.0.1",
		ServerPort:      port,
		Database:        dbName,
		CreateIfMissing: true,
	})
	if err != nil {
		t.Fatalf("dolt.New against running test container: %v", err)
	}

	if err := store.SetConfig(ctx, "issue_prefix", prefix); err != nil {
		store.Close()
		t.Fatalf("Failed to set issue_prefix: %v", err)
	}
	if err := store.SetMetadata(ctx, "_project_id", projectID); err != nil {
		store.Close()
		t.Fatalf("Failed to set _project_id metadata: %v", err)
	}

	t.Cleanup(func() {
		store.Close()
		dropFixTestDatabase(dbName, port)
	})
	return store
}

// dropFixTestDatabase drops a test database (best-effort cleanup).
func dropFixTestDatabase(dbName string, port int) {
	dsn := doltutil.ServerDSN{Host: "127.0.0.1", Port: port, User: "root"}.String()
	db, err := sql.Open("mysql", dsn)
	if err != nil {
		return
	}
	defer db.Close()
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	//nolint:gosec // G201: dbName is generated by test (fixtest_ + random hex)
	_, _ = db.ExecContext(ctx, fmt.Sprintf("DROP DATABASE IF EXISTS `%s`", dbName))
}

// TestFixFunctions_RequireBeadsDir verifies all fix functions properly validate
// that a .beads directory exists before attempting fixes.
func TestFixFunctions_RequireBeadsDir(t *testing.T) {
	funcs := []struct {
		name string
		fn   func(string) error
	}{
		{"GitHooks", GitHooks},
		{"DatabaseVersion", DatabaseVersion},
		{"SchemaCompatibility", SchemaCompatibility},
		{"ChildParentDependencies", func(dir string) error { return ChildParentDependencies(dir, false) }},
		{"OrphanedDependencies", func(dir string) error { return OrphanedDependencies(dir, false) }},
		{"OrphanedChildCounters", func(dir string) error { return OrphanedChildCounters(dir, false) }},
	}

	for _, tc := range funcs {
		t.Run(tc.name, func(t *testing.T) {
			// Use a temp directory without .beads
			dir := t.TempDir()
			err := tc.fn(dir)
			if err == nil {
				t.Errorf("%s should return error for missing .beads directory", tc.name)
			}
		})
	}
}

// TestOrphanedChildCounters_FixDeletesOnlyOrphans verifies the destructive
// half of the #4539 fix: OrphanedChildCounters must DELETE exactly the
// dangling child_counters/wisp_child_counters rows and leave every row with
// a live parent untouched. TestFixFunctions_RequireBeadsDir only covers the
// missing-.beads-dir error path; nothing previously exercised the DELETE
// itself against a live store.
//
// Unlike the sibling TestDependencyKeys_RekeysAndRemovesLeftovers
// (dep_keys_test.go), which uses requireFixDoltContainer and connects to
// the shared BEADS_DOLT_PORT container, this test clears BEADS_DOLT_PORT
// and has dolt.New auto-start its own local `dolt sql-server` subprocess
// via the local `dolt` binary (internal/doltserver) — the same mechanism
// `bd init` uses in production — no Docker required.
func TestOrphanedChildCounters_FixDeletesOnlyOrphans(t *testing.T) {
	testutil.RequireDoltBinary(t)

	// TestMain sets BEADS_DOLT_PORT process-wide when Docker is available,
	// which suppresses the .beads/dolt-server.port file openFixDB needs to
	// reach this test's auto-started server. Clear it, as the dolt package's
	// own tests do.
	t.Setenv("BEADS_DOLT_PORT", "")

	dir := t.TempDir()
	beadsDir := filepath.Join(dir, ".beads")
	if err := os.MkdirAll(beadsDir, 0755); err != nil {
		t.Fatalf("create .beads: %v", err)
	}

	// Unique database name: the local server/process may outlive a single run.
	h := sha256.Sum256([]byte(t.Name() + fmt.Sprintf("%d", time.Now().UnixNano())))
	dbName := "fixorphancc_" + hex.EncodeToString(h[:6])

	// Seed metadata.json up front (with the target database name already
	// set) so OrphanedChildCounters' own openDoltDB(beadsDir) → configfile.Load
	// call — a separate connection from the one below — resolves the same
	// server/database this test seeds.
	// project_id matched between metadata.json and the database so
	// verifyFixTargetIdentity (mybd-2qegi) doesn't reject this fix call as an
	// unverifiable target — OrphanedChildCounters is a destructive fix entry
	// point and so goes through guardFixTarget like its siblings.
	projectID := configfile.GenerateProjectID()
	seedCfg := &configfile.Config{Database: "dolt", DoltDatabase: dbName, ProjectID: projectID}
	if err := seedCfg.Save(beadsDir); err != nil {
		t.Fatalf("save initial config: %v", err)
	}

	ctx := context.Background()
	store, err := dolt.New(ctx, &dolt.Config{
		Path:            filepath.Join(beadsDir, "dolt"),
		BeadsDir:        beadsDir,
		Database:        dbName,
		CreateIfMissing: true,
		MaxOpenConns:    1,
		AutoStart:       true,
	})
	if err != nil {
		t.Fatalf("dolt.New with local auto-start: %v", err)
	}
	defer func() { _ = store.Close() }()

	if err := store.SetConfig(ctx, "issue_prefix", "tst"); err != nil {
		t.Fatalf("SetConfig(issue_prefix): %v", err)
	}
	if err := store.SetMetadata(ctx, "_project_id", projectID); err != nil {
		t.Fatalf("SetMetadata(_project_id): %v", err)
	}

	// Live parent + live wisp: their child_counters/wisp_child_counters rows
	// must survive the fix untouched.
	liveIssue := &types.Issue{ID: "tst-live", Title: "live parent", Status: types.StatusOpen, Priority: 1, IssueType: types.TypeEpic}
	if err := store.CreateIssue(ctx, liveIssue, "test"); err != nil {
		t.Fatalf("CreateIssue live parent: %v", err)
	}
	liveWisp := &types.Issue{ID: "tst-wisp-live", Title: "live wisp parent", Status: types.StatusOpen, Priority: 2, IssueType: types.TypeTask, NoHistory: true}
	if err := store.CreateIssue(ctx, liveWisp, "test"); err != nil {
		t.Fatalf("CreateIssue live wisp parent: %v", err)
	}

	db := store.UnderlyingDB()
	if _, err := db.ExecContext(ctx, "INSERT INTO child_counters (parent_id, last_child) VALUES (?, 1)", liveIssue.ID); err != nil {
		t.Fatalf("insert live child_counters row: %v", err)
	}
	if _, err := db.ExecContext(ctx, "INSERT INTO wisp_child_counters (parent_id, last_child) VALUES (?, 1)", liveWisp.ID); err != nil {
		t.Fatalf("insert live wisp_child_counters row: %v", err)
	}

	// Orphaned rows: FK checks disabled per-connection so the dangling insert
	// succeeds (same trick as the detection tests in validation_test.go's
	// sibling doctor package, TestCheckOrphanedChildCountersDB_*).
	const orphanParent = "tst-missing-parent"
	const orphanWispParent = "tst-missing-wisp-parent"
	if _, err := db.ExecContext(ctx, "SET FOREIGN_KEY_CHECKS = 0"); err != nil {
		t.Fatal(err)
	}
	if _, err := db.ExecContext(ctx, "INSERT INTO child_counters (parent_id, last_child) VALUES (?, 3)", orphanParent); err != nil {
		t.Fatalf("insert orphaned child_counters row: %v", err)
	}
	if _, err := db.ExecContext(ctx, "INSERT INTO wisp_child_counters (parent_id, last_child) VALUES (?, 2)", orphanWispParent); err != nil {
		t.Fatalf("insert orphaned wisp_child_counters row: %v", err)
	}
	if _, err := db.ExecContext(ctx, "SET FOREIGN_KEY_CHECKS = 1"); err != nil {
		t.Fatal(err)
	}

	countRows := func(t *testing.T, query string) int {
		t.Helper()
		var got int
		if err := db.QueryRowContext(ctx, query).Scan(&got); err != nil {
			t.Fatalf("query %q: %v", query, err)
		}
		return got
	}

	if got := countRows(t, "SELECT COUNT(*) FROM child_counters"); got != 2 {
		t.Fatalf("child_counters before fix = %d, want 2 (1 live + 1 orphaned)", got)
	}
	if got := countRows(t, "SELECT COUNT(*) FROM wisp_child_counters"); got != 2 {
		t.Fatalf("wisp_child_counters before fix = %d, want 2 (1 live + 1 orphaned)", got)
	}

	// OrphanedChildCounters (validation.go) opens its own connection via
	// openDoltDB → configfile.Load, which is server-mode only (remotes.go's
	// openFixDB always dials MySQL). seedCfg above already points that config
	// at the same local server/database this test just seeded — with the
	// ambient BEADS_DOLT_PORT cleared above, the port comes from the
	// .beads/dolt-server.port file the auto-start wrote.
	if err := OrphanedChildCounters(dir, false); err != nil {
		t.Fatalf("OrphanedChildCounters: %v", err)
	}

	// (a) orphans gone from both tables.
	if got := countRows(t, "SELECT COUNT(*) FROM child_counters"); got != 1 {
		t.Errorf("child_counters after fix = %d, want 1 (orphan removed)", got)
	}
	if got := countRows(t, "SELECT COUNT(*) FROM wisp_child_counters"); got != 1 {
		t.Errorf("wisp_child_counters after fix = %d, want 1 (orphan removed)", got)
	}
	if got := countRows(t, fmt.Sprintf("SELECT COUNT(*) FROM child_counters WHERE parent_id = '%s'", orphanParent)); got != 0 {
		t.Errorf("orphaned child_counters row for %s still present after fix", orphanParent)
	}
	if got := countRows(t, fmt.Sprintf("SELECT COUNT(*) FROM wisp_child_counters WHERE parent_id = '%s'", orphanWispParent)); got != 0 {
		t.Errorf("orphaned wisp_child_counters row for %s still present after fix", orphanWispParent)
	}

	// (b) valid rows untouched.
	if got := countRows(t, fmt.Sprintf("SELECT COUNT(*) FROM child_counters WHERE parent_id = '%s'", liveIssue.ID)); got != 1 {
		t.Errorf("live child_counters row for %s missing after fix", liveIssue.ID)
	}
	if got := countRows(t, fmt.Sprintf("SELECT COUNT(*) FROM wisp_child_counters WHERE parent_id = '%s'", liveWisp.ID)); got != 1 {
		t.Errorf("live wisp_child_counters row for %s missing after fix", liveWisp.ID)
	}

	// (c) the check now reports ok — mirrors the doctor package's
	// checkOrphanedChildCountersDB against the same connection.
	var orphanCount int
	const checkQuery = `
		SELECT COUNT(*) FROM (
			SELECT cc.parent_id FROM child_counters cc
			LEFT JOIN issues i ON cc.parent_id = i.id
			WHERE i.id IS NULL
			UNION ALL
			SELECT wcc.parent_id FROM wisp_child_counters wcc
			LEFT JOIN wisps w ON wcc.parent_id = w.id
			WHERE w.id IS NULL
		) orphans`
	if err := db.QueryRowContext(ctx, checkQuery).Scan(&orphanCount); err != nil {
		t.Fatalf("post-fix orphan check query: %v", err)
	}
	if orphanCount != 0 {
		t.Errorf("post-fix orphan check found %d orphan(s), want 0 (check should now report ok)", orphanCount)
	}

	// Re-running the fix on an already-clean store must be a safe no-op.
	if err := OrphanedChildCounters(dir, false); err != nil {
		t.Fatalf("OrphanedChildCounters (second run, no-op expected): %v", err)
	}
	if got := countRows(t, "SELECT COUNT(*) FROM child_counters"); got != 1 {
		t.Errorf("child_counters after no-op re-run = %d, want 1", got)
	}
	if got := countRows(t, "SELECT COUNT(*) FROM wisp_child_counters"); got != 1 {
		t.Errorf("wisp_child_counters after no-op re-run = %d, want 1", got)
	}
}

func TestChildParentDependencies_NoBadDeps(t *testing.T) {
	dir := t.TempDir()
	store := newFixTestStore(t, dir, "bd")
	ctx := context.Background()

	// Create issues
	for _, id := range []string{"bd-abc", "bd-abc.1", "bd-xyz"} {
		issue := &types.Issue{
			ID:        id,
			Title:     "Issue " + id,
			Status:    types.StatusOpen,
			IssueType: types.TypeTask,
			CreatedAt: time.Now(),
		}
		if err := store.CreateIssue(ctx, issue, "test"); err != nil {
			t.Fatal(err)
		}
	}

	// Add a non-child→parent dependency (bd-abc.1 blocks bd-xyz)
	dep := &types.Dependency{
		IssueID:     "bd-abc.1",
		DependsOnID: "bd-xyz",
		Type:        types.DepBlocks,
		CreatedAt:   time.Now(),
		CreatedBy:   "test",
	}
	if err := store.AddDependency(ctx, dep, "test"); err != nil {
		t.Fatal(err)
	}

	// Run fix - should find no bad deps
	err := ChildParentDependencies(dir, false)
	if err != nil {
		t.Errorf("ChildParentDependencies failed: %v", err)
	}

	// Verify the good dependency still exists
	db := store.UnderlyingDB()
	var count int
	if err := db.QueryRow("SELECT COUNT(*) FROM dependencies").Scan(&count); err != nil {
		t.Fatal(err)
	}
	if count != 1 {
		t.Errorf("Expected 1 dependency, got %d", count)
	}
}

func TestChildParentDependencies_FixesBadDeps(t *testing.T) {
	dir := t.TempDir()
	store := newFixTestStore(t, dir, "bd")
	ctx := context.Background()

	// Create issues
	for _, id := range []string{"bd-abc", "bd-abc.1", "bd-abc.1.2"} {
		issue := &types.Issue{
			ID:        id,
			Title:     "Issue " + id,
			Status:    types.StatusOpen,
			IssueType: types.TypeTask,
			CreatedAt: time.Now(),
		}
		if err := store.CreateIssue(ctx, issue, "test"); err != nil {
			t.Fatal(err)
		}
	}

	// Add child→parent blocking dependencies (anti-pattern)
	for _, d := range []struct{ from, to string }{
		{"bd-abc.1", "bd-abc"},
		{"bd-abc.1.2", "bd-abc"},
		{"bd-abc.1.2", "bd-abc.1"},
	} {
		dep := &types.Dependency{
			IssueID:     d.from,
			DependsOnID: d.to,
			Type:        types.DepBlocks,
			CreatedAt:   time.Now(),
			CreatedBy:   "test",
		}
		if err := store.AddDependency(ctx, dep, "test"); err != nil {
			t.Fatal(err)
		}
	}

	// Run fix
	err := ChildParentDependencies(dir, false)
	if err != nil {
		t.Errorf("ChildParentDependencies failed: %v", err)
	}

	// Verify all bad dependencies were removed
	db := store.UnderlyingDB()
	var count int
	if err := db.QueryRow("SELECT COUNT(*) FROM dependencies").Scan(&count); err != nil {
		t.Fatal(err)
	}
	if count != 0 {
		t.Errorf("Expected 0 dependencies after fix, got %d", count)
	}
}

// TestChildParentDependencies_PreservesParentChildType verifies that legitimate
// parent-child type dependencies are NOT removed (only blocking types are removed).
func TestChildParentDependencies_PreservesParentChildType(t *testing.T) {
	dir := t.TempDir()
	store := newFixTestStore(t, dir, "bd")
	ctx := context.Background()

	// Create issues
	for _, id := range []string{"bd-abc", "bd-abc.1", "bd-abc.2"} {
		issue := &types.Issue{
			ID:        id,
			Title:     "Issue " + id,
			Status:    types.StatusOpen,
			IssueType: types.TypeTask,
			CreatedAt: time.Now(),
		}
		if err := store.CreateIssue(ctx, issue, "test"); err != nil {
			t.Fatal(err)
		}
	}

	// Add a legitimate parent-child dep (should be preserved by the fix)
	pcDep := &types.Dependency{
		IssueID:     "bd-abc.2",
		DependsOnID: "bd-abc",
		Type:        types.DepParentChild,
		CreatedAt:   time.Now(),
		CreatedBy:   "test",
	}
	if err := store.AddDependency(ctx, pcDep, "test"); err != nil {
		t.Fatal(err)
	}

	// Add a child→parent blocking dep (anti-pattern to be removed by the fix).
	// AddDependency rejects type changes on the same key pair, so we use a
	// different child (bd-abc.1) that has no prior parent-child dep.
	blockDep := &types.Dependency{
		IssueID:     "bd-abc.1",
		DependsOnID: "bd-abc",
		Type:        types.DepBlocks,
		CreatedAt:   time.Now(),
		CreatedBy:   "test",
	}
	if err := store.AddDependency(ctx, blockDep, "test"); err != nil {
		t.Fatal(err)
	}

	// Run fix
	err := ChildParentDependencies(dir, false)
	if err != nil {
		t.Fatalf("ChildParentDependencies failed: %v", err)
	}

	// Verify only 'blocks' type was removed, 'parent-child' preserved.
	// bd-abc.2→bd-abc (parent-child) survives; bd-abc.1→bd-abc (blocks) is removed.
	db := store.UnderlyingDB()

	var blocksCount int
	if err := db.QueryRow("SELECT COUNT(*) FROM dependencies WHERE type = 'blocks'").Scan(&blocksCount); err != nil {
		t.Fatal(err)
	}
	if blocksCount != 0 {
		t.Errorf("Expected 0 'blocks' dependencies after fix, got %d", blocksCount)
	}

	var parentChildCount int
	if err := db.QueryRow("SELECT COUNT(*) FROM dependencies WHERE type = 'parent-child'").Scan(&parentChildCount); err != nil {
		t.Fatal(err)
	}
	if parentChildCount != 1 {
		t.Errorf("Expected 1 'parent-child' dependency preserved, got %d", parentChildCount)
	}
}
