// Code generated by gen (flatfile typed-unsupported shell); DO NOT EDIT.

package flatfile

import (
	"context"
	"github.com/steveyegge/beads/internal/storage"
)

// unsupportedDoltStorage is the generated typed-unsupported shell for storage.DoltStorage.
// Every method returns *storage.ErrUnsupported; embed it and override the
// real slice. DO NOT hand-edit — regenerate with `go generate ./...`.
type unsupportedDoltStorage struct{}

func (unsupportedDoltStorage) AddFederationPeer(_ context.Context, _ *storage.FederationPeer) (err error) {
	err = errUnsupported("AddFederationPeer")
	return
}

func (unsupportedDoltStorage) GetFederationPeer(_ context.Context, _ string) (_ *storage.FederationPeer, err error) {
	err = errUnsupported("GetFederationPeer")
	return
}

func (unsupportedDoltStorage) ListFederationPeers(_ context.Context) (_ []*storage.FederationPeer, err error) {
	err = errUnsupported("ListFederationPeers")
	return
}

func (unsupportedDoltStorage) RemoveFederationPeer(_ context.Context, _ string) (err error) {
	err = errUnsupported("RemoveFederationPeer")
	return
}

// NOTE: partial shell (144 methods skipped); the embedding composite must assert storage.DoltStorage itself.
