#!/usr/bin/env python3
"""Regenerate .github/scripts/proxied-cmd-test-shards.txt by cost-balancing.

Discovery must stay in step with proxied-test-shard.sh: both select the
TestProxiedServer* and TestServerMode* entry points, which share the
requireSharedProxiedServer gate and the shared dolt sql-server.

Two cost models, selected by --weights (default: inits, unchanged from
before this flag existed — the committed 15-shard block for the legacy
pr-risk.yml/main.yml jobs was generated this way and is NOT regenerated by
this script's --weights=duration path; it stays frozen so those jobs' shard
assignment keeps its exact current behavior):

  --weights=inits (default): bd-init count (newSharedProxiedProject
    occurrences) per top-level function — a cheap static proxy for
    wall-time that undercounts a test whose cost is dominated by what it
    does per init rather than how many inits it runs (see the two
    known-expensive entries in the committed 15-shard manifest's header).

  --weights=duration: measured wall-time from
    scripts/ci/proxied_test_durations.json (that file's header explains its
    provenance and limits). A function missing from that file — a test
    added since it was last captured — falls back to its inits cost times
    the file's "seconds_per_init_fallback" ratio, so a brand-new test still
    gets a plausible seconds-shaped weight instead of a unit-mismatched one.

Either way, tests are packed into TOTAL shards longest-processing-time-first
(heaviest first onto the currently lightest shard) so the heaviest shard's
total is minimized. Prints the manifest block to stdout.

Usage: gen_proxied_shard_manifest.py [total_shards] [--weights=inits|duration]
"""
import argparse
import glob
import json
import os
import re
import sys

func_re = re.compile(r'^func (Test(?:ProxiedServer|ServerMode)[A-Za-z0-9_]+)\(')


def discover_inits_cost():
    """Return {test_name: bd-init count}, floored at 1 (setup/teardown)."""
    costs = {}
    for path in glob.glob('cmd/bd/*_test.go'):
        with open(path) as fh:
            lines = fh.readlines()
        cur = None
        for ln in lines:
            m = func_re.match(ln)
            if m:
                cur = m.group(1)
                costs.setdefault(cur, 0)
            elif ln.startswith('func '):
                cur = None
            if cur:
                costs[cur] += ln.count('newSharedProxiedProject')
    for k in costs:
        costs[k] = max(costs[k], 1)
    return costs


def duration_cost(inits):
    """Return {test_name: seconds}, from the committed duration capture,
    falling back to inits * seconds_per_init_fallback for an undated test."""
    durations_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'proxied_test_durations.json')
    with open(durations_path) as fh:
        data = json.load(fh)
    measured = data['tests']
    fallback_ratio = data['seconds_per_init_fallback']
    costs = {}
    for name, cost in inits.items():
        costs[name] = measured[name] if name in measured else cost * fallback_ratio
        costs[name] = max(costs[name], 0.001)
    return costs


def pack(costs, total):
    """LPT bin-pack costs into `total` shards. Returns (shards, loads)."""
    order = sorted(costs, key=lambda k: (-costs[k], k))
    shards = [[] for _ in range(total)]
    loads = [0.0] * total
    for name in order:
        i = loads.index(min(loads))
        shards[i].append(name)
        loads[i] += costs[name]
    return shards, loads


def render(total, shards, weights):
    out = []
    out.append('# Proxied-server cmd test shard manifest.')
    out.append('#')
    out.append('# Format: <total_shards> <shard_number> <top_level_test_name>')
    out.append('#')
    if weights == 'inits':
        out.append(f'# {total}-shard split, bin-packed longest-processing-time-first by')
        out.append('# estimated cost (bd-init count; per-init migration chains dominate).')
        out.append(f'# Regenerate with scripts/ci/gen_proxied_shard_manifest.py {total} after adding,')
        out.append('# splitting, or reweighting TestProxiedServer*/TestServerMode*')
        out.append('# functions. Newly-added tests not listed here hash-distribute via')
        out.append('# proxied-test-shard.sh.')
        out.append('#')
        out.append('# This file is generated: notes added here are erased by the next')
        out.append('# regeneration. Add them to the generator instead. Known blind spots')
        out.append('# of the cost proxy (it counts inits, not the work done per init):')
        out.append('#')
        out.append('#   TestProxiedServerListSortRetiresTheWalk is the most expensive')
        out.append('#   entry and one of the cheapest-looking: off a single init it seeds')
        out.append('#   1400 rows and walks the listing three ways. It is the measurement')
        out.append('#   behind the claim that sort=priority retires the client-side walk,')
        out.append('#   so it has to run on PRs.')
        out.append('#')
        out.append('#   TestProxiedServerServeReadParity is the CLI/HTTP read parity')
        out.append('#   oracle, the behavioural half of the anti-drift claim. It being in')
        out.append('#   this lane, and this lane being required by the PR Risk CI gate,')
        out.append('#   is what makes that claim enforced on PRs rather than asserted in')
        out.append('#   a doc comment.')
        out.append('#')
        out.append(f'# This {total}-shard block is frozen for pr-risk.yml/main.yml\'s legacy')
        out.append('# fork/push jobs: do not regenerate it even after adding tests (they')
        out.append('# hash-distribute until a maintainer chooses to reweight on purpose).')
    else:
        out.append(f'# {total}-shard split for the Bazel-only proxied-server tier')
        out.append('# (bazel-proxied in .github/workflows/bazel.yml), bin-packed')
        out.append('# longest-processing-time-first by measured wall-time from')
        out.append('# scripts/ci/proxied_test_durations.json (see that file for')
        out.append('# provenance and its "relative weight, not absolute SLA" caveat).')
        out.append(f'# Regenerate with scripts/ci/gen_proxied_shard_manifest.py {total} --weights=duration')
        out.append('# after adding, splitting, or reweighting TestProxiedServer*/')
        out.append('# TestServerMode* functions — ideally after refreshing')
        out.append('# proxied_test_durations.json too. Newly-added tests not listed here')
        out.append('# hash-distribute via proxied-test-shard.sh using the same fallback')
        out.append('# ratio documented in proxied_test_durations.json.')
        out.append('#')
        out.append('# This file is generated: notes added here are erased by the next')
        out.append('# regeneration. Add them to the generator or the durations file')
        out.append('# instead.')
    out.append('')
    for i in range(total):
        for name in sorted(shards[i]):
            out.append(f'{total} {i + 1} {name}')
        out.append('')
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('total_shards', nargs='?', type=int, default=15)
    ap.add_argument('--weights', choices=['inits', 'duration'], default='inits')
    args = ap.parse_args()

    inits = discover_inits_cost()
    costs = inits if args.weights == 'inits' else duration_cost(inits)

    shards, loads = pack(costs, args.total_shards)
    out = render(args.total_shards, shards, args.weights)

    unit = 'inits' if args.weights == 'inits' else 's'
    fmt = (lambda v: str(v)) if args.weights == 'inits' else (lambda v: f'{v:.1f}')
    sys.stderr.write(f'shard loads (est. {unit}, weights={args.weights}): ' +
                      ', '.join(f'{i + 1}:{fmt(loads[i])}' for i in range(args.total_shards)) + '\n')
    sys.stderr.write(f'heaviest shard: {fmt(max(loads))} {unit}\n')
    print('\n'.join(out).rstrip() + '\n', end='')


if __name__ == '__main__':
    main()
