package main

import (
	"bytes"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/dolthub/dolt/go/libraries/doltcore/servercfg"
	"github.com/dolthub/dolt/go/libraries/utils/filesys"
	"gopkg.in/yaml.v3"

	"github.com/steveyegge/beads/internal/config"
	"github.com/steveyegge/beads/internal/configfile"
	"github.com/steveyegge/beads/internal/doltserver"
	"github.com/steveyegge/beads/internal/storage/dbproxy/proxy"
)

// archiveLevelSupportNoticeFormat is the one-time stderr notice emitted when
// generating a fresh managed-server config.yaml against an external dolt
// that predates auto_gc_behavior.archive_level support. Never fires for an
// existing config.yaml (ensureProxiedServerConfig only renders on first
// bootstrap), so this is not a per-invocation warning.
const archiveLevelSupportNoticeFormat = "Info: external dolt predates archive_level config support (need >= Dolt %s); " +
	"this managed server's background auto-GC may still produce zstd archives.\n"

// managedProxiedServerConfigMarker is written as a YAML comment header on
// every config.yaml Beads itself generates (renderProxiedServerConfig).
// YAML comments are ignored by Dolt's own parser, so this is invisible to
// dolt sql-server; Beads uses it to tell its own config.yaml apart from a
// user-supplied one (env var / sidecar custom path, or a default-path file
// pre-dating this marker) before deciding whether it is safe to
// automatically reconcile auto_gc_behavior.archive_level on load
// (reconcileManagedProxiedServerConfig) versus leaving the file untouched
// and only warning (warnUnmanagedProxiedServerConfig). See
// gastownhall/beads#4986.
const managedProxiedServerConfigMarker = "# Managed by Beads - safe to delete (will be regenerated). " +
	"Hand edits may be lost on upgrade. See gastownhall/beads#4986.\n"

// isManagedProxiedServerConfig reports whether body was generated by
// renderProxiedServerConfig (carries managedProxiedServerConfigMarker as
// its first line) rather than hand-written or supplied by a user.
func isManagedProxiedServerConfig(body []byte) bool {
	return bytes.HasPrefix(body, []byte(managedProxiedServerConfigMarker))
}

// reconcileManagedProxiedServerConfig parse-modify-rewrites a Beads-managed
// config.yaml's auto_gc_behavior.archive_level so it matches the resolved
// external dolt's capability, preserving every other field (including
// port, and sibling auto_gc_behavior fields such as a user-set "enable")
// by round tripping through the servercfg YAML structs rather than string
// surgery:
//
//   - archiveLevelSupported and archive_level is absent: set it to 0
//     (auto-GC stays enabled), creating the auto_gc_behavior block if
//     necessary but preserving any existing sibling fields on it.
//   - !archiveLevelSupported and archive_level is present: clear only
//     archive_level, so a dolt downgrade cannot hard-fail on
//     yaml.UnmarshalStrict seeing a key its own older YAMLConfig struct
//     does not have. The block itself is only removed if doing so leaves
//     it entirely empty (no enable, no incremental_file_size either).
//
// Deliberately inspects only ArchiveLevel_, not "the whole block is
// present" — an earlier version of this function tested
// cfg.BehaviorConfig.AutoGCBehavior != nil, which meant a block carrying
// only a user-set "enable" (no archive_level) both failed to gain
// archive_level when supported, and lost its "enable" setting entirely
// when the whole block was stripped on an unsupported binary.
//
// Returns the rewritten bytes (with the marker re-prepended) and whether a
// rewrite is actually needed; callers should skip the write when unchanged.
func reconcileManagedProxiedServerConfig(body []byte, archiveLevelSupported bool) ([]byte, bool, error) {
	cfg, err := servercfg.NewYamlConfig(body)
	if err != nil {
		return nil, false, fmt.Errorf("parse: %w", err)
	}

	gc := cfg.BehaviorConfig.AutoGCBehavior
	hasArchiveLevel := gc != nil && gc.ArchiveLevel_ != nil
	changed := false

	switch {
	case archiveLevelSupported && !hasArchiveLevel:
		if gc == nil {
			gc = &servercfg.AutoGCBehaviorYAMLConfig{}
			cfg.BehaviorConfig.AutoGCBehavior = gc
		}
		archiveLevel := 0
		gc.ArchiveLevel_ = &archiveLevel
		changed = true
	case !archiveLevelSupported && hasArchiveLevel:
		gc.ArchiveLevel_ = nil
		if isAutoGCBehaviorEmpty(gc) {
			cfg.BehaviorConfig.AutoGCBehavior = nil
		}
		changed = true
	}

	if !changed {
		return body, false, nil
	}

	rendered, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, false, fmt.Errorf("render: %w", err)
	}
	return append([]byte(managedProxiedServerConfigMarker), rendered...), true, nil
}

// isAutoGCBehaviorEmpty reports whether gc has no fields set at all, i.e.
// it is now safe to omit the whole auto_gc_behavior block rather than
// render an empty "{}" or "auto_gc_behavior:" with no children.
func isAutoGCBehaviorEmpty(gc *servercfg.AutoGCBehaviorYAMLConfig) bool {
	return gc.Enable_ == nil && gc.ArchiveLevel_ == nil && gc.IncrementalFileSize_ == nil
}

// warnUnmanagedProxiedServerConfig emits a one-line notice for a config.yaml
// Beads never rewrites (no managedProxiedServerConfigMarker: a user-custom
// path, or a default-path file predating this marker). It surfaces the same
// two risks reconcileManagedProxiedServerConfig fixes automatically for a
// Beads-owned config, without ever touching the file:
//   - archiveLevelSupported and the key is absent: zstd auto-GC may still
//     be active; tell the user how to opt in.
//   - !archiveLevelSupported and the key is present: the resolved external
//     dolt may refuse to start on this file (yaml.UnmarshalStrict on an
//     unrecognized key).
//
// cfg must be the ALREADY-PARSED config (via servercfg.YamlConfigFromFile,
// not NewYamlConfig on raw bytes) — callers own an unmanaged file's parse,
// and that parse must be interpolation-aware (see the ensureProxiedServerConfig
// doc comment on why raw-bytes parsing is wrong for these files).
func warnUnmanagedProxiedServerConfig(path string, cfg servercfg.ServerConfig, archiveLevelSupported bool) {
	hasKey := cfg.AutoGCBehavior() != nil
	switch {
	case archiveLevelSupported && !hasKey:
		fmt.Fprintf(os.Stderr,
			"Warning: %s is not Beads-managed (no marker); zstd auto-GC may still be active. "+
				"To opt in, add 'auto_gc_behavior: {archive_level: 0}' under the top-level 'behavior:' key.\n",
			path)
	case !archiveLevelSupported && hasKey:
		fmt.Fprintf(os.Stderr,
			"Warning: %s sets auto_gc_behavior.archive_level, but the resolved external dolt predates support "+
				"for it (need >= Dolt %s); the server may refuse to start. Remove the key or upgrade dolt.\n",
			path, doltserver.MinDoltVersionForArchiveLevelConfig)
	}
}

const (
	proxiedServerConfigName = "config.yaml"
	proxiedServerLogName    = "server.log"
)

func proxiedServerRoot(beadsDir string) string {
	return doltserver.ResolveDoltDir(beadsDir)
}

func proxiedServerConfigPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerConfigName)
}

func proxiedServerLogPath(beadsDir string) string {
	return filepath.Join(proxiedServerRoot(beadsDir), proxiedServerLogName)
}

func envOrAbsJoin(envName, beadsDir string) string {
	p := os.Getenv(envName)
	if p == "" {
		return ""
	}
	if filepath.IsAbs(p) {
		return p
	}
	return filepath.Join(beadsDir, p)
}

func resolveProxiedServerRootPath(beadsDir string) (string, error) {
	if p := envOrAbsJoin("BEADS_PROXIED_SERVER_ROOT_PATH", beadsDir); p != "" {
		return p, nil
	}
	info, err := configfile.LoadProxiedServerClientInfo(beadsDir)
	if err != nil {
		return "", err
	}
	if p := info.ResolvedRootPath(beadsDir); p != "" {
		return p, nil
	}
	return proxiedServerRoot(beadsDir), nil
}

func resolveProxiedServerConfigPath(beadsDir string) (path string, isCustom bool, err error) {
	if p := envOrAbsJoin("BEADS_PROXIED_SERVER_CONFIG", beadsDir); p != "" {
		return p, true, nil
	}
	info, err := configfile.LoadProxiedServerClientInfo(beadsDir)
	if err != nil {
		return "", false, err
	}
	if p := info.ResolvedConfigPath(beadsDir); p != "" {
		return p, true, nil
	}
	root, err := resolveProxiedServerRootPath(beadsDir)
	if err != nil {
		return "", false, err
	}
	return filepath.Join(root, proxiedServerConfigName), false, nil
}

func resolveProxiedServerLogPath(beadsDir string) (path string, isCustom bool, err error) {
	if p := envOrAbsJoin("BEADS_PROXIED_SERVER_LOG", beadsDir); p != "" {
		return p, true, nil
	}
	info, err := configfile.LoadProxiedServerClientInfo(beadsDir)
	if err != nil {
		return "", false, err
	}
	if p := info.ResolvedLogPath(beadsDir); p != "" {
		return p, true, nil
	}
	root, err := resolveProxiedServerRootPath(beadsDir)
	if err != nil {
		return "", false, err
	}
	return filepath.Join(root, proxiedServerLogName), false, nil
}

// ensureProxiedServerConfig resolves (creating if needed) the managed
// sql-server config.yaml. archiveLevelSupported gates whether a freshly
// generated config sets auto_gc_behavior.archive_level: 0 (see
// renderProxiedServerConfig).
//
// Parsing an EXISTING file (custom path, or a pre-marker default-path file
// we only warn about — never a Beads-managed one) MUST go through
// servercfg.YamlConfigFromFile, not servercfg.NewYamlConfig on raw bytes:
// YamlConfigFromFile expands ${VAR}-style environment placeholders before
// parsing (servercfg/env_interpolate.go), and a user's custom config is
// entitled to use that syntax the same way `dolt sql-server --config`
// itself would accept it. NewYamlConfig on raw bytes is only safe for a
// Beads-managed file (marker present), because Beads itself never writes
// interpolation syntax into a file it generates.
func ensureProxiedServerConfig(beadsDir string, archiveLevelSupported bool) (string, error) {
	path, isCustom, err := resolveProxiedServerConfigPath(beadsDir)
	if err != nil {
		return "", err
	}

	if isCustom {
		info, err := os.Stat(path)
		if err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: %w", path, err)
		}
		if !info.Mode().IsRegular() {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: not a regular file", path)
		}
		cfg, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path)
		if err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: custom config %s: parse: %w", path, err)
		}
		// A custom config is always user-owned, whether or not it happens to
		// carry the marker — never rewritten, only warned about.
		warnUnmanagedProxiedServerConfig(path, cfg, archiveLevelSupported)
		return path, nil
	}

	root := filepath.Dir(path)
	if err := os.MkdirAll(root, config.BeadsDirPerm); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: mkdir %s: %w", root, err)
	}

	switch _, err := os.Stat(path); {
	case err == nil:
		// The marker is a literal comment line Beads itself writes and never
		// interpolates — safe to check on raw bytes before deciding which
		// (interpolation-aware or not) parse path applies below.
		body, err := os.ReadFile(path) //nolint:gosec // G304: path is Beads' own default config.yaml location, not user-request input
		if err != nil {
			return "", fmt.Errorf("ensureProxiedServerConfig: read existing config %s: %w", path, err)
		}
		if isManagedProxiedServerConfig(body) {
			// Beads-managed: never carries interpolation syntax, so raw-bytes
			// parsing (inside reconcileManagedProxiedServerConfig) is safe and
			// avoids a redundant interpolation pass.
			reconciled, changed, rerr := reconcileManagedProxiedServerConfig(body, archiveLevelSupported)
			if rerr != nil {
				return "", fmt.Errorf("ensureProxiedServerConfig: reconcile managed config %s: %w", path, rerr)
			}
			if changed {
				if werr := atomicWriteFile(path, reconciled); werr != nil {
					return "", fmt.Errorf("ensureProxiedServerConfig: rewrite managed config %s: %w", path, werr)
				}
			}
		} else {
			// Pre-marker default-path file (created by a Beads version before
			// this fix) — treat like a custom config: interpolation-aware
			// parse, never rewritten, only warned about.
			cfg, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path)
			if err != nil {
				return "", fmt.Errorf("ensureProxiedServerConfig: existing config %s: parse: %w", path, err)
			}
			warnUnmanagedProxiedServerConfig(path, cfg, archiveLevelSupported)
		}
		return path, nil
	case !os.IsNotExist(err):
		return "", fmt.Errorf("ensureProxiedServerConfig: stat %s: %w", path, err)
	}

	port, err := proxy.PickFreePort()
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: pick free port: %w", err)
	}

	if !archiveLevelSupported {
		fmt.Fprintf(os.Stderr, archiveLevelSupportNoticeFormat, doltserver.MinDoltVersionForArchiveLevelConfig)
	}

	body, err := renderProxiedServerConfig(port, archiveLevelSupported)
	if err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: render YAML: %w", err)
	}
	if err := atomicWriteFile(path, body); err != nil {
		return "", fmt.Errorf("ensureProxiedServerConfig: write %s: %w", path, err)
	}
	return path, nil
}

// Validators below emit source-neutral errors. Callers wrap with whichever
// label is meaningful at their site: CLI callers prepend the flag name
// (e.g. "--proxied-server-config-path"); runtime callers (uow factory, etc.)
// prepend whatever label fits — the path may have come from env var or
// the proxied_server_client_info.json sidecar, not necessarily a flag.

func validateProxiedServerConfig(path string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	if !info.Mode().IsRegular() {
		return fmt.Errorf("%s: not a regular file", path)
	}
	if _, err := servercfg.YamlConfigFromFile(filesys.LocalFS, path); err != nil {
		return fmt.Errorf("%s: parse: %w", path, err)
	}
	return nil
}

func validateProxiedServerRootPath(path string) error {
	switch info, err := os.Stat(path); {
	case err == nil:
		if !info.IsDir() {
			return fmt.Errorf("%s: not a directory", path)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}

func validateProxiedServerLogPath(path string) error {
	parent := filepath.Dir(path)
	parentInfo, err := os.Stat(parent)
	if err != nil {
		return fmt.Errorf("%s: parent directory: %w", path, err)
	}
	if !parentInfo.IsDir() {
		return fmt.Errorf("%s: parent %s is not a directory", path, parent)
	}
	switch info, err := os.Stat(path); {
	case err == nil:
		if !info.Mode().IsRegular() {
			return fmt.Errorf("%s: not a regular file", path)
		}
	case !os.IsNotExist(err):
		return fmt.Errorf("%s: %w", path, err)
	}
	return nil
}

// renderProxiedServerConfig renders the managed sql-server config.yaml. When
// archiveLevelSupported is true it sets auto_gc_behavior.archive_level: 0,
// so this server's background auto-GC writes classic Snappy table files
// instead of zstd archives (gastownhall/beads#4986); auto-GC itself stays
// enabled (the sibling "enable" key is left unset, which Dolt defaults to
// true). When false, the key is omitted entirely — an older external dolt's
// own YAMLConfig struct may not have this field, and Dolt's config loader
// uses yaml.UnmarshalStrict, so an unrecognized key is a hard parse error at
// server startup rather than a silently-ignored one. Callers must gate
// archiveLevelSupported on doltserver.SupportsArchiveLevelConfig.
func renderProxiedServerConfig(port int, archiveLevelSupported bool) ([]byte, error) {
	host := proxiedServerListenerHost
	logLevel := string(servercfg.LogLevel_Info)
	yc := &servercfg.YAMLConfig{
		LogLevelStr: &logLevel,
		ListenerConfig: servercfg.ListenerYAMLConfig{
			HostStr:    &host,
			PortNumber: &port,
		},
	}
	if archiveLevelSupported {
		archiveLevel := 0
		yc.BehaviorConfig.AutoGCBehavior = &servercfg.AutoGCBehaviorYAMLConfig{
			ArchiveLevel_: &archiveLevel,
		}
	}
	body, err := yaml.Marshal(yc)
	if err != nil {
		return nil, err
	}
	return append([]byte(managedProxiedServerConfigMarker), body...), nil
}

const proxiedServerListenerHost = "127.0.0.1"

// TODO: this needs to return a dolt server uow provider as the global
// uow provider used by all commands

//	func newProxiedServerStore(ctx context.Context, cfg *dolt.Config) (storage.DoltStorage, error) {
//		if cfg == nil {
//			return nil, fmt.Errorf("newProxiedServerStore: cfg is nil")
//		}
//		if cfg.BeadsDir == "" {
//			return nil, fmt.Errorf("newProxiedServerStore: cfg.BeadsDir must be set")
//		}
//		if cfg.Database == "" {
//			return nil, fmt.Errorf("newProxiedServerStore: cfg.Database must be set")
//		}
//
//		doltBin, err := exec.LookPath("dolt")
//		if err != nil {
//			return nil, fmt.Errorf("newProxiedServerStore: dolt is not installed (not found in PATH); install from https://docs.dolthub.com/introduction/installation: %w", err)
//		}
//
//		persisted, _ := configfile.Load(cfg.BeadsDir)
//
//		rootPath, isCustomRoot := resolveProxiedServerRootPath(cfg.BeadsDir, persisted)
//		if isCustomRoot {
//			if err := validateProxiedServerRootPath(rootPath); err != nil {
//				return nil, err
//			}
//		}
//
//		configPath, err := ensureProxiedServerConfig(cfg.BeadsDir, persisted)
//		if err != nil {
//			return nil, err
//		}
//
//		logPath, isCustomLog := resolveProxiedServerLogPath(cfg.BeadsDir, persisted)
//		if isCustomLog {
//			if err := validateProxiedServerLogPath(logPath); err != nil {
//				return nil, err
//			}
//		}
//
//		name, email := cfg.CommitterName, cfg.CommitterEmail
//		if name == "" || email == "" {
//			fallbackName, fallbackEmail := proxiedServerCommitter()
//			if name == "" {
//				name = fallbackName
//			}
//			if email == "" {
//				email = fallbackEmail
//			}
//		}
//
//		return doltserver.NewDoltServerStore(
//			ctx,
//			rootPath,
//			cfg.BeadsDir,
//			cfg.Database,
//			name, email,
//			logPath,
//			configPath,
//			proxy.BackendLocalServer,
//			false, // autoSyncToOriginRemote — wired in a future iteration
//			"root",
//			"", // rootPassword: proxy is loopback-only, no auth
//			doltBin,
//		)
//	}
func proxiedServerCommitter() (string, string) {
	name, email := "beads", "beads@localhost"
	if out, err := exec.Command("git", "config", "user.name").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			name = v
		}
	}
	if out, err := exec.Command("git", "config", "user.email").Output(); err == nil {
		if v := strings.TrimSpace(string(out)); v != "" {
			email = v
		}
	}
	return name, email
}
