#!/usr/bin/env bash
# Admin: create project DB + schema + SQL user + start primary gateway + admin invite.
# Prefer: make init-cell   (compat: make bootstrap)
set -euo pipefail
# shellcheck source=common.sh
source "$(cd "$(dirname "$0")" && pwd)/common.sh"

need_cmd python3
need_cmd dolt
ensure_dirs
sync_runtime

GW=$(gateway_bin)
PROV=$(provision_bin)
# Prefer version-matched bd from GATEWAY_SRC (bin/bd-cell). Host `bd` often
# migrates a different schema → gateway reads fail after create.
if [[ -x "$BIN/bd-cell" ]]; then
  BD_BIN="$BIN/bd-cell"
elif command -v bd >/dev/null 2>&1; then
  log "warn: using host bd (may schema-mismatch gateway); prefer make build for bd-cell"
  BD_BIN=$(command -v bd)
else
  die "missing bd-cell — run: make build"
fi
dolt_up || die "Dolt not up — run: make start-dolt"

LAB_ID="${REMOTE_CELL_LAB_ID:-bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb}"
PROJECT_ID="${REMOTE_CELL_PROJECT_ID:-$(python3 - <<'PY'
import uuid
print(uuid.uuid5(uuid.NAMESPACE_URL, "beads-remote-cell-default-v1"))
PY
)}"
# Lab gateway requires beads_perf_lab_ database prefix.
DATABASE="${REMOTE_CELL_DATABASE:-beads_perf_lab_default}"
SUBJECT_ADMIN="${REMOTE_CELL_ADMIN_SUBJECT:-admin}"
PORT="${REMOTE_CELL_GATEWAY_PORT:-7707}"

PW_FILE="$DATA/secrets/pw_default"
TOK_FILE="$DATA/secrets/token_admin"
IDK_FILE="$DATA/secrets/idemp_admin"
if [[ ! -f "$PW_FILE" ]]; then write_secret "$PW_FILE" "$(rand_hex 32)"; fi
if [[ ! -f "$TOK_FILE" ]]; then write_secret "$TOK_FILE" "$(rand_hex 32)"; fi
if [[ ! -f "$IDK_FILE" ]]; then write_secret "$IDK_FILE" "$(rand_hex 32)"; fi
while [[ "$(tr -d '\n' <"$TOK_FILE")" == "$(tr -d '\n' <"$IDK_FILE")" ]]; do
  write_secret "$IDK_FILE" "$(rand_hex 32)"
done
sync_runtime

RT_PW="$REMOTE_CELL_RUNTIME_ROOT/secrets/pw_default"
RT_TOK="$REMOTE_CELL_RUNTIME_ROOT/secrets/token_admin"
RT_IDK="$REMOTE_CELL_RUNTIME_ROOT/secrets/idemp_admin"
QUEUE_FILE="$REMOTE_CELL_RUNTIME_ROOT/queues/q_default_admin.db"
# Lab gateway binds queue to idempotency key identity. Wipe queues on each
# init so rotated secrets never leave a silent "queue binding mismatch".
rm -f "$REMOTE_CELL_RUNTIME_ROOT"/queues/q_default_admin.db* \
      "$REMOTE_CELL_RUNTIME_ROOT"/queues/q_default_admin.db.lock \
      "$DATA"/queues/* 2>/dev/null || true
mkdir -p "$REMOTE_CELL_RUNTIME_ROOT/queues" "$DATA/queues"

log "ensure database $DATABASE"
(cd "$DATA/dolt-host" && dolt sql -q "CREATE DATABASE IF NOT EXISTS \`$DATABASE\`;" >/dev/null 2>&1) || true

NEED_INIT=1
if (cd "$DATA/dolt-host" && dolt sql -q "USE \`$DATABASE\`; SELECT 1 FROM metadata LIMIT 1;" >/dev/null 2>&1); then
  NEED_INIT=0
  log "schema present — skip bd init"
fi
if [[ "$NEED_INIT" -eq 1 ]]; then
  log "init beads schema via bd (temp dir; no repo pollution)"
  PROVDIR=$(mktemp -d "${TMPDIR:-/tmp}/remote-cell-prov.XXXXXX")
  (
    cd "$PROVDIR"
    # Avoid interactive noise. Lab Dolt uses passwordless root — a leftover
    # BEADS_DOLT_PASSWORD from other tools causes Error 1045.
    export BD_NON_INTERACTIVE=1 CI=true
    unset BEADS_DOLT_PASSWORD BEADS_PROXIED_SERVER_EXTERNAL_PASSWORD || true
    "$BD_BIN" init --non-interactive --server --external \
      --server-host 127.0.0.1 --server-port 13360 --server-user root \
      --database "$DATABASE" --prefix rc >/dev/null
  )
  rm -rf "$PROVDIR"
fi

log "stamp project id $PROJECT_ID"
(cd "$DATA/dolt-host" && dolt sql -q \
  "USE \`$DATABASE\`; INSERT INTO metadata (\`key\`, value) VALUES ('_project_id', '$PROJECT_ID') ON DUPLICATE KEY UPDATE value = VALUES(value);" \
  >/dev/null 2>&1) || true

log "mint project SQL user (cell-provision)"
"$PROV" \
  -host 127.0.0.1 -port 13360 \
  -database "$DATABASE" \
  -project-id "$PROJECT_ID" \
  -lab-id "$LAB_ID" \
  -password-file "$RT_PW" \
  -timeout 90s >/dev/null

# Restart primary gateway cleanly
if [[ -f "$DATA/gateway.pid" ]]; then
  kill "$(cat "$DATA/gateway.pid")" 2>/dev/null || true
  rm -f "$DATA/gateway.pid"
fi
free_port "$PORT"

log "start gateway on 127.0.0.1:$PORT"
nohup "$GW" \
  -database "$DATABASE" \
  -dolt-host 127.0.0.1 -dolt-port 13360 \
  -listen "127.0.0.1:$PORT" \
  -lab-id "$LAB_ID" \
  -project-id "$PROJECT_ID" \
  -password-file "$RT_PW" \
  -token-file "$RT_TOK" \
  -idempotency-key-file "$RT_IDK" \
  -queue "$QUEUE_FILE" \
  -runtime-root "$REMOTE_CELL_RUNTIME_ROOT" \
  -subject "$SUBJECT_ADMIN" \
  -max-open 8 -max-idle 4 \
  >"$DATA/logs/gateway.log" 2>&1 &
echo $! >"$DATA/gateway.pid"
wait_tcp 127.0.0.1 "$PORT" "gateway" 80

umask 077
cat >"$CELL_ENV" <<EOF
# Generated by make init-cell — do not commit
REMOTE_CELL_LAB_ID=$LAB_ID
REMOTE_CELL_PROJECT_ID=$PROJECT_ID
REMOTE_CELL_DATABASE=$DATABASE
REMOTE_CELL_GATEWAY_URL=http://127.0.0.1:$PORT
REMOTE_CELL_GATEWAY_PORT=$PORT
REMOTE_CELL_RUNTIME_ROOT=$REMOTE_CELL_RUNTIME_ROOT
REMOTE_CELL_TOKEN_FILE=$RT_TOK
REMOTE_CELL_ADMIN_TOKEN_FILE=$TOK_FILE
EOF
chmod 600 "$CELL_ENV"

cat >"$DATA/public/remote.json" <<EOF
{
  "experimental": true,
  "gateway_url": "http://127.0.0.1:$PORT",
  "project_id": "$PROJECT_ID",
  "note": "Non-secret. Copy into a repo as .beads/remote.json. Tokens are per-person invites only."
}
EOF

ADMIN_INVITE="$DATA/invites/admin.env"
cat >"$ADMIN_INVITE" <<EOF
# Remote cell invite (admin) — do not commit
BEADS_GATEWAY_URL=http://127.0.0.1:$PORT
BEADS_PROJECT_ID=$PROJECT_ID
BEADS_TOKEN=$(tr -d '\n' <"$TOK_FILE")
BEADS_SUBJECT=$SUBJECT_ADMIN
EOF
chmod 600 "$ADMIN_INVITE"

# ports registry
echo "admin $PORT" >"$DATA/ports.tsv"

log "init-cell complete"
log "  gateway: http://127.0.0.1:$PORT"
log "  project: $PROJECT_ID"
log "  invite:  $ADMIN_INVITE"
log "  public:  $DATA/public/remote.json"
log "next: make smoke && make prove"
